name: Windows (Direct3D12)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Force Update Submodules
        run: |
          git submodule update --init --recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile ArmorPaint
        run: |
          node base/make -g direct3d11 --compile

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArmorPaint-Windows
          path: build/krom
